audio_input:
  filename: "/home/mvg/Music/ayetwin.wav"
  a_freq: 440
  low_freq: 16 # just under Cn0 lowest note on 88 key
  high_freq: 7903 # just over Bn8, highest note on a 88 key
  stretch: 6
  duration: 169

video_properties:
  output_filename: "go.mp4"
  framerate: 60
  resolution_width: 1920
  resolution_height: 1080

intermediate_file:
  filename: "ayetwin.npy"
  extraction_type: "FFT"