audio_input:
  filename: "/home/mvg/Music/lopsidewalz.wav"
  a_freq: 443.5
  low_freq: 59
  high_freq: 4000
  stretch: 10
  duration: 90

video_properties:
  output_filename: "go.mp4"
  framerate: 30
  resolution_width: 480
  resolution_height: 300

intermediate_file:
  filename: "lopsidewalz.npy"