audio_input:
  filename: "/home/mvg/Music/slowass.wav"
  a_freq: 440
  low_freq: 16 # just under Cn0 lowest note on 88 key
  high_freq: 7903 # just over Bn8, highest note on a 88 key
  stretch: 6
  duration: 20

video_properties:
  output_filename: "go.mp4"
  framerate: 30
  resolution_width: 1920
  resolution_height: 1200

intermediate_file:
  filename: "slowass.npy"
  extraction_type: "CROSS-COR"