audio_input:
  filename: "/home/mvg/Music/verselaflamme.wav"
  a_freq: 440
  low_freq: 15
  stretch: 7
  duration: 15

video_properties:
  output_filename: "go.mp4"
  framerate: 30
  resolution_width: 480
  resolution_height: 300

intermediate_file:
  filename: "im.npy"