audio_input:
  filename: "/home/mvg/Music/verselaflamme.wav"
  a_freq: 440
  low_freq: 15
  stretch: 10

video_properties:
  output_filename: "go.mp4"
  framerate: 24
  resolution_width: 1920
  resolution_height: 1080